[build]
builder = "nixpacks"

[deploy]
startCommand = "node index.mjs"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
numReplicas = 1
